apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: ecommerce-abtest
type: Opaque
stringData:
  POSTGRES_PASSWORD: "dashpass"
  DATABASE_PASSWORD: "dashpass"
---
apiVersion: v1
kind: Secret
metadata:
  name: dashboard-secret
  namespace: ecommerce-abtest
type: Opaque
stringData:
  SECRET_KEY: "717de09da767a91c002e8c45fc35844a8e380af1695a6c4db595ab043e6232c8"
